### PR TITLE
Fix replay issue with third party domains

### PR DESCRIPTION
**Pull request by inderpartap**
Issue - #3241 

### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [X] Squash commits so it looks sane
- [ ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/main/docs in another PR
- [X] Verify that the test works by running `npm test` and test linting by `npm run lint`

Got the following errors with npm test (not sure if they are related)-
1) should report error
2) should contain grafana options
3) should contain graphite options
4) should contain influxdb options

### Description
Fixing bug where `--chrome.blockDomainsExcept` flag collides with the WebPageReplay functionality.

`blockDomainsExcept` uses the same functionality which is used to route the traffic back to the WebPageReplay server. These overlap and collide, which results in 3rd Party domains still coming in when `REPLAY=true`.

#### Fix:
We would dynamically generate the `execnode` command to handle the blockDomainExcept parameters. Currently, we route all the traffic (*) to localhost during replay, which is the main reason why 3rd party domains are still working. 
The fix is to create an array of all the domains provided with the `--chrome.blockDomainsExcept` flag and map only those domains to the localhost. This would only allow traffic from first-party domains to localhost and block all others.

In the scenario where the replay is true but the blockDomainsExcept flag is not set, we would use the existing functionality to map all traffic to localhost.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @inderpartap cool, let me test it, I have been busy with some other stuff the last days.

**Comment by soulgalore** [comment]
Looks good. To make it easier to maintain I wanna move the code to NodeJS (I think we could integrate it into Browsertime directly), I'll have a go this weekend, if it works, I'll give you the cred :) If to doesn't I'll merge this. Thanks for contribution, really cool!

**Comment by soulgalore** [comment]
Hi @inderpartap inspired by your fix I fixed it directly in Browsertime in https://github.com/sitespeedio/browsertime/pull/1532 . The reason is that maintaining things in bash is harder than NodeJs (at least for me). Early versions of sitespeed.io was written in bash :)

All cred to you @inderpartap I'll thank you in the changelog for your fix!

**Comment by inderpartap** [comment]
Thanks a lot, @soulgalore. I wasn't sure about how to update the `execnode` command through NodeJs 😅 but that's a nice solution. 

Glad I could help.

**Pull request closed without merging**
