### PR TITLE
Add StatsD support (with bulking)

### PR DESCRIPTION
**Pull request by omrilotan**
I'm optimistic about the comment in issue #777:
> ❝  If we want StatsD to work we need PR that makes it configurable. ❞

### StatsD Support
Send graphite data via StatsD, Lintening on UDP connections (DGRAM) via `graphite.statsd` [boolean]

### Limit bulk sizes
Avoid `EMSGSIZE` errors from services limiting data size (like default StatsD) by setting a `graphite.bulkSize` [?number]

## Technical implementation
I have created a graphite sender superclass, supporting bulkSize feature on both default Graphite sender and the new StatsD sender.

The plugin's index (select sender) and data generator (determine format) use an explicit check (`helpers/is-statsd` module), `graphite.statsd` option must equal exactly to `true`.

## examples

| Existing settings (no statsd and no bulk) | Setting statsd to true and bulkSize to 20
| --- | ---
|  |

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @omrilotan ah super cool, let us have a look the coming days! One small thing that isn't obvious from the docs is that _docs/documentation/sitespeed.io/configuration/config.md_ is automatically generated when we do a release (that way we can merge things and then push the new release and update the docs at the same time), so if you can remove that change that will be perfect. It will automatically change when we push the release.

Also just FYI: master is now the coming 7.0 so it will not be released until ... before the summer :) But let us work in the PR here first and then we can also move it to the 6.x branch so we can release it.

Best
Peter

**Comment by omrilotan** [comment]
I'll be happy to apply to 6.x.x after review

**Comment by soulgalore** [comment]
Hi @omrilotan thanks for a really well worked through PR! 

The only thing for me was using inheritance, I used to work a lot with Java a long time ago and that made me allergic to inheritance, but I guess that is a problem on my side only :)

Thanks again!

**Comment by omrilotan** [comment]
Thank you for your quick responses, @soulgalore, should I introduce this change to another branch to include it in 6.x.x?

**Comment by soulgalore** [comment]
For me it is ok to release it in 7 (before summer whenever that happens), but if you feel like it, it would be no problem to add it to 6.x. Thanks again @omrilotan !

**Pull request merged**
