### PR TITLE
Configurable metrics keys

### PR DESCRIPTION
**Pull request by soulgalore**
First step to list and configure metrics.

Test it out and lets discuss the workflow before we merge it.

<pre>
Metrics
  --metrics.list        List all possible metrics in the data folder
                        (metrics.txt).                [boolean] [default: false]
  --metrics.filterList  List all configured filters for metrics in the data
                        folder (configuredMetrics.txt)[boolean] [default: false]
  --metrics.filter      Add/change/remove filters for metrics. If you want to
                        send all metrics, use: *+ . If you want to remove all
                        current metrics and send only the coach score: *-
                        coach.summary.score.*                            [array]
</pre>

#943

### CODE REVIEW

**Comment by soulgalore** [comment]
I need help testing this but I should probably add some examples how to add metrics :)

**Comment by beenanner** [comment]
@soulgalore will test this one as soon as I can get my desktop setup the laptop wasn't cutting it for me anymore.

**Comment by beenanner** [comment]
I've just tested and confirmed it's only sending what I asked when I pass the single metric.

`bin/sitespeed.js https://www.sitespeed.io/ -b chrome --graphite.host localhost --metrics.filter *- pagexray.pageSummary.requests --metrics.list --metrics.filterList`

```
browsertime.pageSummary.-
browsertime.summary.-
coach.summary.-
coach.pageSummary.-
pagexray.pageSummary.requests
pagexray.summary.-
domains.summary.-
```

Though passing multiple ` bin/sitespeed.js https://www.sitespeed.io/ -b chrome --graphite.host localhost --metrics.filter *- pagexray.pageSummary.requests pagexray.pageSummary.contentTypes.css.contentSize --metrics.list --metrics.filterList` seems incorrect as it ignored the first request metric for `pagexray.pageSummary.requests`

```
browsertime.pageSummary.-
browsertime.summary.-
coach.summary.-
coach.pageSummary.-
pagexray.pageSummary.contentTypes.css.contentSize
pagexray.summary.-
domains.summary.-
```

I wonder if we could have a text configuration file that you could just pass in same format as what is outputted by configuredMetrics.txt. I think passing them via the command line while OK if you wanted only a few metrics I would think it would be a bit cumbersome for the larger sets of data capturing that are being cherry picked. The file could just be used as the configured metrics. Stinks for the minimal capture runs but would standardize on a configuration file.

``` 
  coach.pageSummary.*
  pagexray.pageSummary.requests
  pagexray.pageSummary.contentTypes.css.contentSize
````

**Comment by beenanner** [comment]
@soulgalore  I just pushed a commit to fix the second issue where adding an additional metrics that was within the same namespace would override the existing one.

`bin/sitespeed.js https://www.sitespeed.io/ -b chrome --graphite.host localhost --metrics.filter *- pagexray.pageSummary.requests pagexray.pageSummary.contentTypes.css.contentSize --metrics.list --metrics.filterList`

```
browsertime.pageSummary.-
browsertime.summary.-
coach.summary.-
coach.pageSummary.-
pagexray.pageSummary.requests
pagexray.pageSummary.contentTypes.css.contentSize
pagexray.summary.-
domains.summary.-
```

Everything seem to be working as far as I can tell.

`bin/sitespeed.js https://www.sitespeed.io/ -b chrome --graphite.host localhost --metrics.filter *- coach.pageSummary.advice.accessibility.adviceList.altImages.score coach.pageSummary.advice.bestpractice.adviceList.doctype.weight browsertime.pageSummary.browserScripts.1.coach.coachAdvice.advice.accessibility.adviceList.landmarks.score browsertime.pageSummary.browserScripts.1.coach.coachAdvice.advice.timings.navigationTimings.* browsertime.pageSummary.statistics.timings.navigationTiming.domLoading.median browsertime.pageSummary.statistics.coach.coachAdvice.advice.info.*.mean browsertime.summary.navigationTiming.domainLookupEnd.max --metrics.list --metrics.filterList`

```
browsertime.pageSummary.browserScripts.1.coach.coachAdvice.advice.accessibility.adviceList.landmarks.score
browsertime.pageSummary.browserScripts.1.coach.coachAdvice.advice.timings.navigationTimings.*
browsertime.pageSummary.statistics.timings.navigationTiming.domLoading.median
browsertime.pageSummary.statistics.coach.coachAdvice.advice.info.*.mean
browsertime.summary.navigationTiming.domainLookupEnd.max
coach.summary.-
coach.pageSummary.advice.accessibility.adviceList.altImages.score
coach.pageSummary.advice.bestpractice.adviceList.doctype.weight
pagexray.pageSummary.-
pagexray.summary.-
domains.summary.-
```

**Comment by soulgalore** [comment]
@beenanner cool. but can people understand how it works? :)

**Comment by beenanner** [comment]
We definitely would need to focus on clearly documenting this format and how it works. @soulgalore I guess the other option would be a JSON object, but that seems like that could get pretty verbose. Though it would be in a format that everyone should understand. :-)

**Comment by soulgalore** [comment]
I'll merge this tomorrow Friday prepping for the first beta this weekend :)

**Comment by soulgalore** [comment]
Lets merge this to make sure that #1145 will work with the fix.

**Pull request merged**
