### PR TITLE
Bump co2 to 0.5.0 and remove tests now in external co2 module

### PR DESCRIPTION
**Pull request by mrchrisadams**
Hi Peter,

Now that we have the CO2 module that contains all the logic and tests extracted it doesn't seem like the tests we had in the plugin add very much. 

You reckon we can get rid of them now?

If so, I'll tidy up this PR for you to merge in.

### CODE REVIEW

**Comment by soulgalore** [comment]
Yes @mrchrisadams lets remove, better if you have them in co2!

**Comment by soulgalore** [comment]
One test failing but because of instability on Windows I think so I'll just rerun it.

@mrchrisadams do you have more co2 changes coming or can I release it? :)

**Comment by mrchrisadams** [comment]
Hi Peter!

I think we're at a point where there's enough to release, and I'm in favour of doing so.

So, I think it might be time to invoke the  :shipit:  squirrel :)

**Comment by mrchrisadams** [comment]
@soulgalore just to be clear here. I'm leaving the merging this PR in and releasing to you for this, as I haven't done a release of sitespeed yet, and well… I have a blog post to write about this now :)

**Comment by soulgalore** [comment]
Great @mrchrisadams :)

**Comment by soulgalore** [comment]
@mrchrisadams I'll release this tonight and ping you on Slack when its done.

**Pull request merged**
