### PR TITLE
Add waitScript logic to screenshots

### PR DESCRIPTION
**Pull request by jzoldak**
@soulgalore I wasn't sure - do you prefer issues with PRs that fix them, or is just the PR ok?

### CODE REVIEW

**Comment by soulgalore** [comment]
oops I totally missed this sorry, going out in an release in a day or two.

**Comment by jzoldak** [comment]
awesome, thx.

**Comment by jzoldak** [comment]
@soulgalore thx for merging my PRs in. We are now happily running on v3.10.0.

**Comment by soulgalore** [comment]
sorry that it took so long time, have had a hard time the last month to find the time to give the love to sitespeed.io

**Comment by soulgalore** [comment]
and thanks again for all the PR:s :)

**Pull request merged**
