### PR TITLE
Fix for when wpt returns no data and a 200 response - Temp Fixes #1685

### LINKED ISSUE #1685: WebPageTest missing data breaks a run
We sometimes gets error when running WebPageTest against NYT:

screen shot 2017-07-31 at 06 56 22

The problem is that WebPageTest [misses data from one run](https://www.webpagetest.org/result/170730_W6_6c0ba8a9efbf1193ccdde74d950ed0d5/).

We should check for that in the JSON we get back.

https://www.webpagetest.org/jsonResult.php?test=170730_W6_6c0ba8a9efbf1193ccdde74d950ed0d5

### PR DESCRIPTION
**Pull request by beenanner**
Temp fix for #1685

### CODE REVIEW

**Comment by beenanner** [comment]
Better diff to ignore the whitespace. ;-)

https://github.com/sitespeedio/sitespeed.io/pull/1687/files?w=1

**Comment by beenanner** [comment]
Hmm analyzer may be a better place for this patch.

**Comment by soulgalore** [comment]
I think this is ok so we pickup the runs that worked? Do we also need to do a fix the template or does it work?

**Comment by beenanner** [comment]
Let me do a bit more testing before we merge. Hopefully I can verify everything today. :-)

**Comment by soulgalore** [comment]
What about adding a error log entry when it happens so people know?

**Comment by beenanner** [comment]
In terms of the HTML everything is still working just no data. The screenshot error still surfaces in the logs, but if you think it should @soulgalore I can add another log entry for the zero data if the if condition fails. Let me know and I'll can update it tonight.

screen shot 2017-08-02 at 1 11 10 pm
screen shot 2017-08-02 at 1 11 16 pm

**Comment by soulgalore** [comment]
cool, whatabout adding a log entry missing data or whatever the gui says in wpt?

**Comment by beenanner** [comment]
Yes let me add that tonight then I'll merge this change for the next release.

**Comment by soulgalore** [comment]
great!

**Pull request merged**
