### PR TITLE
Plugin tab polish

### PR DESCRIPTION
**Pull request by tobli**
Tweaks to how plugins tabs are rendered in displayed. Fixes edge case crash.

### CODE REVIEW

**Comment by soulgalore** [comment]
I think this PR changed the behavior? When I click on a tab, the browser scrolls down to the content, so clicking on tabs becomes a little jumpy (I tested in Chrome). Was that the intention? :)

**Comment by soulgalore** [comment]
Looks better, great! One last thing: We miss the # in the URL now so you cannot share URL to specific tabs as before (see https://examples.sitespeed.io/5.0/2017-04-24-04-44-04/pages/en.wikipedia.org/wiki/Main_Page/index.html#browsertime). However maybe we should move to a "page per tab" solution, I'm not sure.

**Comment by tobli** [comment]
Latest commit fixes the # fragment issue.

**Comment by soulgalore** [comment]
perfect let us merge it tonight then.

**Pull request merged**
