### PR TITLE
Add support for influxDBV2

### LINKED ISSUE #3197: Influx Cloud (v2) support
I've read the documentation and other issues on here, and I've noticed in this [reply](https://github.com/sitespeedio/sitespeed.io/issues/3015#issuecomment-635153227) that sitespeed leverages the [node-influx ](https://github.com/node-influx/node-influx/) package for connectivity with influxDB.

However node-influx aren't advertising compatibility with InfluxDB 2, suggesting to use the official [influxdb-client-js](https://github.com/influxdata/influxdb-client-js/) package instead. (https://github.com/node-influx/node-influx/issues/483#issuecomment-597657588) 

Is this on the roadmap to support the new influxdb client library?
Thanks

### PR DESCRIPTION
**Pull request by Damien-Ar**
## Description

Add support for Influxdb version 2

Should close  #3197

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @Damien-Ar thanks for the PR! I'll test it later this week, don't know exact date but going to put high prio on it!

**Comment by soulgalore** [comment]
This week I'm gonna check this, I need to add some tests, today we only do some runs against Graphite in our GitHub action and it would be nice to test both Influx versions.

**Comment by soulgalore** [comment]
I'm still struggling to get my env up and running @Damien-Ar what's the easiest way to setup InfluxDB with a database and everything up and ready, I tried the instructions in https://hub.docker.com/_/influxdb but still fails. Can you share an example? Thanks :)

**Comment by Damien-Ar** [comment]
Hi,
I use this docker-compose:
```
services:
  influxdb:
    image: ${INFLUXDB_IMAGE_VERSION}
    container_name: ${INFLUXDB_HOST}
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG_NAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET_NAME}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}
 
 volumes:
  influxdb-storage:
```
with these variables in a `.env` file nearby
```
INFLUXDB_HOST=influxdb
INFLUXDB_PORT=8086
INFLUXDB_RETENTION=24w

INFLUXDB_ORG_NAME=default
INFLUXDB_USERNAME=default
INFLUXDB_PASSWORD=defaultinfluxdb
INFLUXDB_BUCKET_NAME=db0
INFLUXDB_IMAGE_VERSION=influxdb:2.1.1
```

You'll need to open the GUI, connect to the db and grab a token (data -> API token) to give it to sitespeed. (There is probably a way to automate this, I just haven't looked for it)
Using a json file to config sitespeed, it look like this with my default variables: 
```
{
    ...
    "influxdb": {
        "version": 2,
        "host": "influxdb",
        "port": 8086,
        "database": "db0",
        "token": "TOKEN",
        "org": "default"
    }
}
```
Hope it help, and sorry for the delay

**Comment by eQza** [comment]
Hey guys, any idea when this will be approved? Will be really good feature to add. 

Cheers

**Comment by soulgalore** [comment]
Hi @Damien-Ar sorry I'm in the middle of moving the code to esm, hopefully it will be done this month and then I'll release this together with that change.

**Comment by eQza** [comment]
any love for this please? <3

**Comment by soulgalore** [comment]
I hope I can merge this after the next weekend, sorry for the long wait, the rewrite I'm doing has took so long time.

**Comment by boitcex** [comment]
It would be really great to see InfluxDB V2.x support ASAP. Thank you a lot for your contribution.

**Comment by boitcex** [comment]
Hi @Damien-Ar, @soulgalore!
I have tested sitespeed from your custom branch (https://github.com/Zenika/sitespeed.io/tree/update-influxdb) locally and found that **Visual Metrics** were not recorded in the HTML report and InfluxDb as well. Just want to let you know about it. The screen
2023-02-07_14h36_51
 with example is attached

**Comment by Damien-Ar** [comment]
@boitcex, you commented a few day ago about some differences in the html reports generated from the version in my branch. I didn't manage duplicate this issue, do you still have the issue ?

**Comment by boitcex** [comment]
@Damien-Ar no, I did it by mistake. Please ignore it

**Comment by boitcex** [comment]
@Damien-Ar yes,I can use your branch. I just create a custom sitespeed and use "org" and can connect to InfluxDB.
Configuration example:
  "influxdb": {
    "protocol": "https",
    "host": "host_example",
    "port": "443",
	"version": 2,
	"org": "bucket_id",
	"token": "token_example",
    "annotationScreenshot": true,
    "database": "sitespeed_test"
  }

**Comment by Damien-Ar** [comment]
ok, I'm glad that you found a workaround. The option in the documentation was `organisation` and not `org`, I'll fix that but you will have to update your config if you pull the latest commit

**Comment by boitcex** [comment]
@Damien-Ar thanks, will do. I hope to see your fork into main site speed. Thanks to @soulgalore in advance)

**Comment by boitcex** [comment]
Hi @soulgalore!
I hope all is well.
Could you please share ETA for merging the custom branch "Zenika:update-influxdb" into the main?
I am really waiting for this.
Thank you in advance.

**Comment by soulgalore** [comment]
Hi my plan was to push it this week but that never happened. It's been a couple of thing I'm waiting on:
1. Push Browsertime 17 (that is done)
2. Integrate 17 in sitespeed.io and switch to ESM (that what I'm working on now)
3. Merge.
4. Probably (but I haven't decided yet) to push a couple of plugins to a standalone plugin, that would be great so that people that do not Influx/GCS etc not need to install them. But I haven't make up my mind yet.
5. Release a first alpha of the new sitespeed.io that will realistically happen the week of 27 of February.

**Comment by soulgalore** [comment]
There's a lot of testing for me todo to release next sitespeed.io, gonna take it step by step since the change I've done is quite large and each plugin needs to be tested. For the influx plugin, wanna see if we can update the GitHub action so we run tests against both v1 and v2.

**Comment by soulgalore** [comment]
Hi @boitcex it would be great if we could automate some tests for both v1 and v2 in a GitHub action. If someone could contribute a setup that would be great, that way I would feel more comfortable releasing it. We have a simple test for Graphite in https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/linux.yml#L32 and https://github.com/sitespeedio/sitespeed.io/blob/main/.github/workflows/linux.yml#L64 and I think something similar for v1 and v2 would be good.

**Comment by soulgalore** [comment]
Also its merged but to release it I need to do https://github.com/sitespeedio/sitespeed.io/issues/3776

**Comment by boitcex** [comment]
@soulgalore  I can create tests for both v1 and v2 in a GitHub action, but I need your assistance in this one. Could we have a quick chat?

**Comment by boitcex** [comment]
I have created a test at main, but I do not have access:
remote: Permission to sitespeedio/sitespeed.io.git denied to boitcex.
fatal: unable to access 'https://github.com/sitespeedio/sitespeed.io.git/': The requested URL returned error: 403

**Comment by soulgalore** [comment]
Hi @boitcex thanks great. Fork the project and make a PR. https://docs.github.com/en/get-started/quickstart/fork-a-repo

**Comment by boitcex** [comment]
image
--influxdb.organisation  -> --influxdb.organi**Z**ation

**Pull request merged**
