### PR TITLE
Correct way of creating relative urls in html site

### PR DESCRIPTION
**Pull request by tobli**
- rename relativePathFromUrl to pathFromRootToPageDir to make it more obvious what it does.
- join relative url path with / instead of using the path module (should make paths work on all OSes).
- remove path parameter for url run pages, since it wasn't used.
- make StorageManager constructor signature follow node conventions (options last) and add some StorageManager tests.

### CODE REVIEW

**Comment by tobli** [comment]
Since I've fixed some path separator related issues, I'm hoping this could fix #1003. Would love some help verifying on Windows.
Ping @beenanner, @rschoessler

**Comment by beenanner** [comment]
@tobli will try to test it tonight!

**Comment by beenanner** [comment]
@tobli verified this branch fixes the issue with #1003!

**Comment by tobli** [comment]
👍

**Pull request merged**
