### PR TITLE
First pass at supporting URL aliases for #1326

### PR DESCRIPTION
**Pull request by beenanner**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [x] Check that your change/fix has corresponding unit tests (if applicable)
- [x] Squash commits so it looks sane
- [x] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs
- [x] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
First pass at adding url-aliases for graphite via URL file

### CODE REVIEW

**Comment by soulgalore** [comment]
Looks cool :) I think we maybe should also add the alias on each individual page? Like "https://www.sitespeed.io/documentation/ a.k.a Documentation" or something?

**Comment by beenanner** [comment]
Yes good idea! I'll add them to the HTML output as well!

**Comment by beenanner** [comment]
@soulgalore what do you think about converting the titles to links and replacing the URL if an alias exists?

pages-alias-column


alias-titles

no-alias-title

**Comment by soulgalore** [comment]
Looks good @beenanner !

**Pull request merged**
