### PR TITLE
Added --summary option(s) to get text summary to stdout

### PR DESCRIPTION
**Pull request by moos**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I'm making a ~~big~~ small change or adding functionality so ~~I've already~~ haven't opened an issue proposing the change to other contributors, so I ~~got~~ hope to get feedback on the idea ~~before~~ even though I took the time to write precious code :)
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [x] Squash commits so it looks sane
- [x] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
This is a fairly small change to get summary results right on the cli console - useful for a quick look or when run as part of larger build process.  It is based on the main summary data in the HTML report.

--summary option:
sitespeed-summary

--summary-detail option:
sitespeed-summary-detail

### CODE REVIEW

**Comment by soulgalore** [comment]
Wow @moos this looks amazing! I will not have time to check the code today, maybe @tobli or @beenanner can have a check before merge, else I'll fix that tomorrow.

**Comment by soulgalore** [comment]
Haven't forgotten this, had hard time to find the time, will merge tonight, maybe just move it to another plugin, haven't had time to check the code too much yet :)

**Comment by moos** [comment]
No problem -- initially I started it as a separate 'text' plugin -- turned out it had a lot in common with the 'html' code, so I ended up moving it there.  This way it simply uses the summaryBoxes that's already generated for html.  To make it independent of 'html' we'd have to make some of the code in html common (helpers, summarizers, etc.)

**Comment by soulgalore** [comment]
yes, I've started now, it's good in a way because we can split things in the html plugin that actually can be separeted and the code will be cleaner in the long run. see if I can get it to work tonight. thanks again for the PR really like the idea getting the summary info out :)

**Comment by soulgalore** [comment]
It was a larger rewrite than I thought, will continue tomorrow.

**Comment by soulgalore** [comment]
This is merged now in master, thanks @moos for the great idea, really like it and combined with https://github.com/sitespeedio/browsertime/pull/189 it will be awesome. I've moved it to separate plugin.

**Pull request closed without merging**
