### PR TITLE
added docs for VNC server

### PR DESCRIPTION
**Pull request by abhagupta**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [ ] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Please describe your pull request and tell us the fix #

Thank you for making sitespeed.io even better!

### CODE REVIEW

**Comment by soulgalore** [comment]
Great, thanks @abhagupta ! I'll merge it later today/tomorrow when I've had time to test, we need to change a couple of things for 4.0.

**Comment by beenanner** [comment]
@abhagupta can you do you mind pulling in master and fixing the conflicts? Thanks!

**Comment by soulgalore** [comment]
I made some changes, I can fix it otherwise, just need to update to the new syntax, can do that tomorrow.

**Comment by abhagupta** [comment]
@beenanner Updated the branch.  Formatted the text as well to match the existing standards.

**Comment by soulgalore** [comment]
thank you @abhagupta !

**Pull request merged**
