### PR TITLE
Add unit to slack summary

### PR DESCRIPTION
**Pull request by lbilhaut**
### Description

This PR adds units to the Slack summary (issue https://github.com/sitespeedio/sitespeed.io/issues/3099)

### CODE REVIEW

**Comment by lbilhaut** [comment]
Great, thanks! I've pushed the changes but I'm still having an issue with the build for Linux browsers. This is not my OS so I'm not familiar with it. I'm wondering if it's because the API key is not valid for CruX (in that case, how to fix it?) or if it's because now, it expects a space between the number and the unit.

**Comment by soulgalore** [comment]
Hi @lbilhaut thanks! Can you just exclude the shrink-wrap from the commit and I'll merge. 

The test failing is the Crome User Experience key that sometimes just fails, so its not related to your change.

**Comment by soulgalore** [comment]
Thank you @lbilhaut !

**Comment by lbilhaut** [comment]
Great, thanks @soulgalore ! That's my very first contribution to an open source project!!! (small step for sitespeedio but a big leap for me!)

**Comment by soulgalore** [comment]
Great :D It will take some time until I release it though, probably next week so I can bundle the release with some more changes. Thanks again!

**Pull request merged**
