### PR TITLE
Possibility to choose test (folder) name instead of current datetime

### PR DESCRIPTION
**Pull request by JeroenVdb**
Add extra parameter to the run command with unique test name. I use this to create URL for the Jenkins Plot plugin: /sitespeed-result/%index%/index.html

```
./bin/sitespeed.io -u http://www.sitespeed.io/ -i build1

Folder: sitespeed.io\sitespeed-result\www.sitespeed.io\build1\index.html
```

sitespeed unique url example in jekins

### CODE REVIEW

**Comment by paulandrieux** [comment]
What about this feature ? Would be great to allow this in 3.0

**Comment by soulgalore** [comment]
it exists in the current version, it was just the pull request thats not needed. I'll update this issue tonight for clarity.

Best
Peter

**Comment by soulgalore** [comment]
Hi again @paulandrieux ,
use the switch <code>--outputFolderName</code> and you can specify where you want it.

Best
Peter

**Comment by paulandrieux** [comment]
Amazing thank you ;)

**Pull request closed without merging**
