### PR TITLE
#2758 - fix: keep selected tab open across runs

### PR DESCRIPTION
**Pull request by amtanq**
#2758 stated the issue of resetting the tab upon page change. This pull request adds a proxy over the navigation links and specifies new page to open with proper tab.

### CODE REVIEW

**Comment by amtanq** [comment]
@soulgalore In my previous pull request, there was the issue of conversion of LF to CRLF, I fixed that issue but in current PR one test linux fails named `Run tests with CruX`. It states that the API key not valid but I don't think my PR has anything related to API key for Crux can you please take a look.
Thank You

**Comment by soulgalore** [comment]
Hi @amtanq sorry about that test, that test use an API key that only seems valid for members of the organisation, I haven't had to look how to set it up so it works for all users. 

Thanks a lot for the fix, I'm gonna release it tomorrow when I had some time to test it!

**Comment by soulgalore** [comment]
Hi @amtanq it looks great. 

I wonder if there's a way to make it work a little bit better  for Chrome? I usually do not use Chrome but I always test it there. If I run a test with many runs for a site with many request (you can test with  `https://www.cnet.com -n 11`) then the lag between showing the summary page and then going to the right tab is much longer than using Firefox/Safari (at least for me. Do you see the same?

**Comment by amtanq** [comment]
@soulgalore I confirm the issue of laggy switches on Chrome. But the issue is arising from the bigger size of generated pages and not an issue in the code of switching tabs.

I have some findings, please verify:
- Size of generated HTML is over quite large, hence the amount of time required for the **DOMContentLoaded** event to get triggered is significant.

- The image verifies that the bottleneck of the issue is slow firing of **DOMContentLoaded** event whereas the page initialization takes well under 1ms.


Benchmark Code:
```javascript
// Started javascript execution
console.time('DOMContentLoaded')

window.addEventListener('DOMContentLoaded', function() {

  // Time taken to fire DOMContentLoaded
  console.timeEnd('DOMContentLoaded')

  // Started subroutine of page switch
  console.time('PageSwitch')
  ...
}

function selectTab(newSelection, updateUrlFragment) {
  ...

  // PageSwitch complete
  console.timeEnd('PageSwitch');

  return false;
}
```

Hence, I think this issue needs a dedicated request as it is not overlapping with the current issue. I'll be happy to get assigned for this issue.

**Comment by soulgalore** [comment]
Thanks @amtanq yes agree, let keep that in a another issue. The blob of HTML is large. It's better when you serve the HTML from a server and configure the HAR to not be included in the file (`--html.fetchHARFiles true`).

**Pull request merged**
