### PR TITLE
Add S3 region option

### PR DESCRIPTION
**Pull request by jjethwa**
Should fix: https://github.com/sitespeedio/sitespeed.io/issues/1468

### CODE REVIEW

**Comment by soulgalore** [comment]
thanks @jjethwa for the PR, will push a release later today!

**Comment by jjethwa** [comment]
Thanks, @soulgalore 

I believe the default region, us-standard, is acceptable, but feel free to modify as needed.  Thanks for the speedy merge 😄

**Comment by soulgalore** [comment]
No it didn't work with us-standard for me with current setup I have, so I changed so we only set it when we got it from the CLI. Does it work for you? :)

**Comment by jjethwa** [comment]
Sounds good!  Thanks :)

**Comment by soulgalore** [comment]
fyi @jjethwa the release will probably happen this weekend, I wanna wait to get a couple of more fixes in, there's one cool thing coming in Browsertime.

**Comment by jjethwa** [comment]
No problem, @soulgalore   Much appreciated 😀

**Pull request merged**
