### PR TITLE
Making string splitting on EOLs versatile

### LINKED ISSUE #640: Splitting URLs from file to array not working (Windows)
**Problem/Reproduction:**
OS: Windows 7
I have a url.txt (created using sublime text 3 build 3083) containing several URLs

```
http://www.toptarif.de/
http://versicherung.toptarif.de/private-krankenversicherung/
http://www.toptarif.de/stromvergleich/
http://www.tarife.de/
```

When running sitespeed.io the following error occurs.
`node bin\sitespeed.js -f urls.txt -d 0 -n 1`

```
http://www.toptarif.de
http://versicherung.toptarif.de/private-krankenversicherung
http://www.toptarif.de/stromvergleich
http://www.tarife.de is not a valid url (you need to include the protocol)
Fix the URL(s) before you continue
```

**Reason**:
Method `getFileAsArray()` in `lib/util/fileHelpers.js` uses `require('os').EOL` to `String.prototype.split()` the file content into an array of URLs. This works great on output files but unfortunately does not work on input files. 
My file returns this string: `http://www.toptarif.de/\nhttp://versicherung.toptarif.de/private-krankenversicherung/\nhttp://www.toptarif.de/stromvergleich/\nhttp://www.tarife.de/`,
And require('os').EOL returns this: `\r\n`
My URL string doesn't contain this line separator :(

OS: 'win32 6.1.7601', Node.js: 'v0.12.0', sitespeed.io: '3.2.7'

### PR DESCRIPTION
**Pull request by yesman82**
This resolves #640 where `require('os').EOL` doesn't always match actual line break.

### CODE REVIEW

**Comment by yesman82** [comment]
What can I do to satisfy AppVeyor?

Travis CI tests work if line with global variables is left out. I need to do that because the variables are secure and cannot be used by me (http://docs.travis-ci.com/user/environment-variables/#Secure-Variables).

**Comment by yesman82** [comment]
I just realized that this merge will only work when browsertime has been  updated *eyes rolling*. This maybe the reason why AppVeyor is bugging me.

**Comment by soulgalore** [comment]
Hey @yesman82 ,
sorry for not doing anything about this PR, I will do it later this week. About AppVeyor, it isn'tsetup ok, so I will remove it for now and make another try setting it up later.

Best
Peter

**Comment by soulgalore** [comment]
Closing this since we have rewritten everything in 4.0. Please create a new PR for changes in 4.0.

**Pull request closed without merging**
