### PR TITLE
Lighthouse

### PR DESCRIPTION
**Pull request by googggat**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [ ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs
- [ ] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Please describe your pull request and tell us the fix #

Thank you for making sitespeed.io even better!

### CODE REVIEW

**Comment by googggat** [comment]
Sorry this is an accidental pull request. Closing

**Comment by lapa182** [comment]
@googggat why an accidental PR? Would be amazing to have it inside sitespeedio!

**Comment by googggat** [comment]
@lapa182 sorry I was only able to obtain a few lighthouse metrics when I stopped. Will need to revisit to make it useful

**Comment by soulgalore** [comment]
I think Lighthouse could be a perfect example of a plugin hosted outside of sitespeed.io. It will work fine as now except the most important missing part is to generate the HTML but we can help out to do the changes in sitespeed.io to make that happen (we don't have a full plan yet though :) ).

**Pull request closed without merging**
