### PR TITLE
#2352 Add ability to run additional start script in Docker container

### PR DESCRIPTION
**Pull request by gidztech**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [ ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs in another PR
- [ ] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Add ability to run an additional start script before running Web Page Replay/SiteSpeed.io scripts. An example use case is adding certificates to the container's local store. See the #2353 for more details.

TODO: Add documentation changes

Thank you for making sitespeed.io even better!

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @gidztech ah cool, let me think about it for a while. I think a generic way of adding things to the start script is great, I just need to try out a couple of ideas I have to do it in alternative ways.

**Comment by gidztech** [comment]
@soulgalore Sure, let know how what options you are considering. 

Side note: I noticed that the way Web Page Replay (WPR) is configured also breaks due to certificate errors, even after installing the certificate in the store. My change above works fine when you don't use WPR. I haven't finished my debugging of this yet, but I think the issue is around the BrowserTime config passed to WPR.

I suspect it might be related to the `host-resolver-rules` flag or somewhere in this area:

```
exec node --max-old-space-size=$MAX_OLD_SPACE_SIZE $SITESPEEDIO --browsertime.firefox.preference security.OCSP.enabled:0 --browsertime.firefox.preference network.dns.forceResolve:127.0.0.1 --browsertime.chrome.args host-resolver-rules="MAP *:$HTTP_PORT 127.0.0.1:$WPR_HTTP_PORT,MAP *:$HTTPS_PORT 127.0.0.1:$WPR_HTTPS_PORT,EXCLUDE localhost" --video --visualMetrics --browsertime.pageCompleteCheck "$WAIT_SCRIPT" --browsertime.connectivity.engine throttle --browsertime.connectivity.throttle.localhost --replay --browsertime.connectivity.profile custom --browsertime.connectivity.latency $LATENCY "$@" &
```

**Comment by soulgalore** [comment]
Sorry @gidztech for being slow on this one. What about something like this:
```
 if [ -f $EXTRA_START_SCRIPT ]
 then
   chmod +x $EXTRA_START_SCRIPT
   $EXTRA_START_SCRIPT
 fi
```

And then run it like  `docker run -e EXTRA_START_SCRIPT=/sitespeed.io/test.sh --rm -v "$(pwd)":/sitespeed.io ...` 

Then the script can be named whatever?

**Comment by gidztech** [comment]
@soulgalore Yeah, that would work. I'll update the PR and test it today. Will need to look at the Web Page Replay issue with certificates I mentioned last year. I think the issue might be related to the proxying.

**Comment by soulgalore** [comment]
I'm thinking this can be done unrelated to the certificate problem, since potentially have other use cases.

**Comment by gidztech** [comment]
Thanks. Sorry I was meant to push it yesterday but couldn’t test it with the certificate file without access to work laptop.

**Comment by soulgalore** [comment]
Np :)

**Pull request merged**
