### PR TITLE
Wpt custom metrics (WIP)

### PR DESCRIPTION
**Pull request by jpvincent**
This is an attempt to add support for the WebPageTest Custom Metrics feature as discussed in the issue #1348

What works : 
- [x] collect the metrics and send Site summary to Graphite
```
sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.customMetrics.firstView.customMetrics.pngNumber.median 7 1481392620
sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.customMetrics.firstView.customMetrics.pngNumber.mean 7 1481392620
sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.customMetrics.firstView.customMetrics.pngNumber.min 7 1481392620
sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.customMetrics.firstView.customMetrics.pngNumber.p90 7 1481392620
sitespeed_io.default.summary.www_sitespeed_io.webpagetest.first_wptdriver-chrome.custom.customMetrics.firstView.customMetrics.pngNumber.max 7 1481392620
```
- [ ] collect the metrics and send Page summary to Graphite
I dont get how to do that, can you help ?
- [ ] add a graph in the default WPT dashboards in grafana 
tested locally : it works, but when exporting the JSON from grafana, the diff file is really different from grafana-setup/dashboards/wptPageSummary.json , so I'm afraid to break things : can you help ?

### original Checklist
- [ ] remove console.log and ```intel.getLogger``` with a name
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [x] Documentation : not needed
- [x] `npm test` OK
- [ ] `npm run lint`

### CODE REVIEW

**Comment by soulgalore** [comment]
Hey @jpvincent cool I can fix that tomorrow before I do release, ok if I just cherry pick the goodies and give you credit, and then I skip the chanel name fixes etc for the coming fix in the future?

Best
Peter

**Comment by jpvincent** [comment]
Sure, I planned to remove it anyway before final commit, they just helped me to understand the code. I first wanted to have a fully functional code.

**Comment by soulgalore** [comment]
ok! or I can send a PR to pvincent:wpt-custom-metrics let me test it out tomorrow and then you can do a clean and squash.

**Comment by soulgalore** [comment]
Had some bandwith so I fixed it in https://github.com/sitespeedio/sitespeed.io/pull/1377 

Sorry @jpvincent it was almost like an impossible mission doing it outside of the project, the miss with no own configuration for summaries was bad and the "custom metric" structure of the WebPageTest json is so clean (I've add a key on the fly now when we find one). 

Closing the PR and thanks for the initial fix and for taking time! Hopefully we will release this early this week.

**Comment by jpvincent** [comment]
Hi no problems, and sorry for the time to answer, I had fully focus on giving a training !

I failed to get how everything really worked in order to use the summary and page summary.
Do you want me to check if all works, or do you have already a branch you're satisfied with, that you'll merge with master ?

**Comment by soulgalore** [comment]
Cool! Well :relaxed: we pushed it in the latest release 4.2.0 I had some time to try it out. If you have time it would super if you can try it out with your metrics to verify that it works for you.

**Comment by jpvincent** [comment]
It does work

**Pull request closed without merging**
