### PR TITLE
Add logging chanel names, for easier debug

### PR DESCRIPTION
**Pull request by jpvincent**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [x] Check that your change/fix has corresponding unit tests (if applicable)
- [x] Squash commits so it looks sane
- [x] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs
- [x] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description

Hi
Here is a small proposal to help debug sitespeed code.
I was trying to know why the webpagetest plugin was not working for me and added more verbosity for the logs. It's not really confortable to read, so here is my proposal : 
- display a prefix for the logs of each module, especially for the plugins part
- add channels for each plugin and for the main sitespeed file

I used the [Intel named logger feature](https://www.npmjs.com/package/intel#getting-a-named-logger) and modified the formater to display the name of the channel.
The default name is 'root'

I have not updated all the files, only the ones I needed in my basic case. First tell me if that sounds like a good idea.

Ultimately we could : 
- add colors ! Intel seems to have planed for it but it requires a huge modification of the Formater and I dont even know if it can auto-choose the color (like my usual JS logger [debug](https://www.npmjs.com/package/debug))
- advice in the plugin documentation to have a channel name, like I did in this PR
- when debugging, being able to listen only for a certain channel, from the CLI (again, like the debug package, it does not seems to exist for Intel)

Tell me what you think

### CODE REVIEW

**Comment by soulgalore** [comment]
hi @jpvincent thanks for the PR! Had a quick chat with @tobli and we been thinking maybe we could automagically set up each channel per plugin, lets get back after the weekend.

Best
Peter

**Comment by jpvincent** [comment]
Fine
automatic would be perfect for the plugins, but for the remaining code (core sitespeed.io, external code like webpagetest or browsertime) it will probably be manual

**Comment by soulgalore** [comment]
For me this will work for now, I can update and add what's needed in every plugin, I think it is crucial to make it easier for people to follow the flow @tobli ?

**Comment by tobli** [comment]
Yep, go go go

**Comment by soulgalore** [comment]
fixed in https://github.com/sitespeedio/sitespeed.io/pull/1544

**Pull request closed without merging**
