### PR TITLE
Added option to write junit file to specified directory instead of console

### PR DESCRIPTION
**Pull request by thebostik**
This was present in 2.5.7 and I still have jenkins set up to grab the junit file from a directory.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hey Stephen, isn't possible to just pipe it to which file you want? When I changed it for 3.0 I thought it was cleaner to put it to the console and then yourself could choose to pipe it to a file. Or do you have a specific problem where it don't work?

Best
Peter

**Comment by thebostik** [comment]
Yes, that's what I did at very first, but noticed at least one occasion other stuff got output, perhaps stderr? I guess as an option I would just do it this way to guarantee it's a valid junit format, though for others needs stdout may work better and didn't want to change your default.

**Comment by soulgalore** [comment]
hmm then there's a defect, all errors should only be sent to the log when you run it like that. do you still have it or can you reproduce it? would like to fox the original problem first :)

**Comment by thebostik** [comment]
Yes, after further consideration and a bit of trying to replicate, it was probably due either to browsertime hanging when trying to use Chrome or troubleshooting phantom2 even I may have just written some stuff to stdout. I switched to a hardcoded file path for junit output almost immediately without too much thought.

I think I could live with redirected stdout junit, just wasn't sure if other stuff might get garbled in.

**Comment by soulgalore** [comment]
ok, lets leave it for now, and then I'll check it later.

**Comment by soulgalore** [comment]
Closing this since we have rewritten everything in 4.0. Please create a new PR for changes in 4.0.

**Pull request closed without merging**
