### PR TITLE
Slowest and heaviest 3rd party assets #1613

### PR DESCRIPTION
**Pull request by soulgalore**
We should look at those keys and check that it really works for Graphite/InfluxDB, haven't done that yet.

### CODE REVIEW

**Comment by beenanner** [comment]
The output looks good. This is what I was testing with. I think the size matches a single asset but the response sizes seemed off even when calculating the sum of all the runs.

`bin/sitespeed.js -b chrome --firstParty ".*(cbsistatic|cnet).*" https://www.cnet.com/`

**Comment by beenanner** [comment]
I did a single run let me know if I'm missing something. :-)

amgdgt com waterfall

vs

amgdgt com slowest

**Comment by soulgalore** [comment]
That's a bug then that I think exists in PageXray, let us look into that.

**Comment by soulgalore** [comment]
PageXray looks ok when I did a quick check, I think the problem is in PerfCascade, check the timings field, the total doesn't match, maybe introduced on 2.0:
screen shot 2017-05-16 at 17 16 53

**Comment by soulgalore** [comment]
Ah ok, the error is in PageXray: We add both SSL and connect time to the total, but SSL is included in the SSL time.

**Comment by soulgalore** [comment]
It should be fixed by 16cfbe5

**Comment by soulgalore** [comment]
The group total that we used needs to be fixed, let me have a go at this later this week.

**Comment by beenanner** [comment]
@soulgalore I also pushed a commit to link each asset to the page run that it originated from instead of the summary page run. This should make it easy to jump to the waterfall for deeper analysis.

**Comment by beenanner** [comment]
For the group total do you mean the domain.html page? I can take a look just let me know. :-)

**Comment by soulgalore** [comment]
Ah sorry @beenanner  that was more for me to remember. I kind of broke the current structure: we group every metric by domain, so that if you test multiple sites, the data are grouped by each site. The total is stats for all sites, and we only send individual groups to TDSB, so with the current structure we will not send the lists to TDSB (and that maybe is fine, let us discuss it).

**Comment by soulgalore** [comment]
Ah I've forgot about this one, I'll see if I can fix this tomorrow.

**Comment by soulgalore** [comment]
I'll have a go this weekend see if I can make it releasable, it is a nice feature.

**Comment by soulgalore** [comment]
Think we are ready to go. We collect per group now but don't send/use it. If we ever need it, lets add it then and keep it as simple as possible for now.

**Pull request merged**
