### PR TITLE
Fixes #1087 -- Make it possible to link to specific tabs on page/run pages

### LINKED ISSUE #1087: Make it possible to link to specific tabs on page/run pages
With the current solution you cannot choose which tab that is open when you access the URL the first time. We should find a way to fix that.

### PR DESCRIPTION
**Pull request by moos**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [x] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests
- [x] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Fixes #1087 -- also makes tabs tab-able (i.e., keyboard nav). Tested on major current browsers & IE9+.

On modern browsers scroll position isn't lost when switching between tabs (it is on IE9).  But when coming to a tab from a bookmark, it'll scroll to the tab location.  This can be avoided by removing the id from the tab anchors -- but it's needed for IE9.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hey @moos thanks, looks super! Can you just squash the commits into one, so I can just merge it so you get the commit?

**Comment by moos** [comment]
Squash done.  (sorry grafana changes got in there due to a rebase -- let me know if you'd like a commit without them.)

**Comment by soulgalore** [comment]
yes can you skip the grafana and make sure the PR are inline with master, then I can just merge and you will get the commit in the history :)

**Comment by moos** [comment]
Done.

**Comment by soulgalore** [comment]
Thanks @moos !!!

**Pull request merged**
