### PR TITLE
Fixed problem with selenium-docker failing

### PR DESCRIPTION
**Pull request by vgoncharenko**
Fixed problem with selenium-docker failing in case for a lot off scenarios in one docker contained without rebutting

This bug caused in case when I tested some urls (10 for example) and in case of failing url 5 for example(random fails sometimes happening in Magento2 =( ), the next steps can't be run with next error:
"Browsertime BrowserError: unknown error: Chrome failed to start: exited abnormallyINFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds."
I investigated this problems and understand that each run of browsertime starts some process: /usr/bin/dbus-daemon
/usr/lib/at-spi2-core/at-spi-bus-launcher
and don't kill after tested each URL (SUCCESS/FAIL case doesn't matter)

### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [ ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/master/docs in another PR
- [ ] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Please describe your pull request and tell us the fix #

Thank you for making sitespeed.io even better!

### CODE REVIEW

**Comment by soulgalore** [comment]
Thank you @vgoncharenko ! 
I think this should be upstream, seems to be some kind of bug in Chrome/Chromedriver? 

I'll test and merge later today and then we can rollout the fix during the weekend (we got some things lined up to be released so that's good). Also I want push this to Browsertime (in master we are working in the new 3.0 so I want sure have it there too).

@tobli have look you too when you have time!
Best
Peter

**Comment by vgoncharenko** [comment]
Yes, in my opinion this bug related to Chromedriver.

Thanks

**Comment by soulgalore** [comment]
Cool, if you have the time it would be super helpful if you could raise Chromedriver ticket too.

I did quick try and I get one extra kill that for a process that is already shutdown:

```
[2018-03-02 09:30:11] INFO: Finished analysing https://www.sitespeed.io/
/start.sh: line 102: kill: (57) - No such process
```

Do you get the same?

**Comment by vgoncharenko** [comment]
Yes, sorry, it happens because I set global trip for background process, but don't forgot to delete after testing, I make this fix some time ago, for my image, and now forgot some details of realisation

**Comment by soulgalore** [comment]
Didn't get the time to merge/release this weekend, let me try to do it later this week, sorry.

**Comment by soulgalore** [comment]
@vgoncharenko you have this merged in your own test right, or do you need this pushed ASAP? Been working on the coming 3.0 of Browsertime and thinking we should add so we do a hard kill of Chrome/Chromedriver if something fails, so it doesn't leave any stuff behind, that fix would be cleaner. 

But let me know, if you need we push it. Else I hope we can release Browsertime sometimes the coming months and then we shortly will release the new sitespeed.io using it.

**Comment by vgoncharenko** [comment]
It's okay for me for waiting browsertime 3 and next version of sitespeed.io, we have your image with this fix in our internal docker hub and use it. And I can create a task for migration to your image after next official release sitespeed.io. Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by soulgalore** [comment]
Let me merge anyway this since we have others that have the same problem. @vgoncharenko do you have any URL we can reference for your fix (just a comment in the code)? Else I see if I can find one.

**Comment by soulgalore** [comment]
thanks @vgoncharenko !

**Comment by vgoncharenko** [comment]
@soulgalore , sorry, my English isn't perfect, can you explain for me part of your sentense about URL? What URL do you need?
And thanks for marge to master. What about 2.x? I can create separate PR if this fix compatible for 2.x.

**Comment by soulgalore** [comment]
Ah no problem, I was unclear. I meant did you come up with your fix yourself or do you have any reference? 

I can add it to Browsertime later on, lets see first when we have a plan for releasing 3.0. 

Thanks again!

**Comment by vgoncharenko** [comment]
@soulgalore , yes, it's my fix

Ok, thanks
Waiting new image)

**Pull request merged**
