### PR TITLE
Update to Chrome 85 and Firefox 80

### PR DESCRIPTION
**Pull request by leipert**
### Your checklist for a pull request to sitespeed.io
Please review the [guidelines for contributing](CONTRIBUTING.md) to this repository.

- [ ] I'm making a big change or adding functionality so I've already opened an issue proposing the change to other contributors, so I got feedback on the idea before took the time to write precious code
- [ ] Check that your change/fix has corresponding unit tests (if applicable)
- [ ] Squash commits so it looks sane
- [ ] Update the documentation https://github.com/sitespeedio/sitespeed.io/tree/main/docs in another PR
- [ ] Verify that the test works by running `npm test` and test linting by `npm run lint`

### Description
Please describe your pull request and tell us the fix #

Thank you for making sitespeed.io even better!

### CODE REVIEW

**Comment by leipert** [comment]
@soulgalore Would you mind having a look? I see that you pushed the latest docker image 😄

**Comment by soulgalore** [comment]
Hi @leipert thanks for the PR, I just pushed the update, sorry. The problem is that when we update the container with a new Chrome, we also need to bump Browsertime to install the matching Chromedriver version. Maybe we can do the smarter in the future.

**Comment by soulgalore** [comment]
I'll let it run for a day and verify that everything looks ok before I push it.

**Comment by leipert** [comment]
No worries, thanks for the update 👍

**Pull request closed without merging**
