### PR TITLE
Shrink URL on Asset HTML report for any relatively long URLs

### PR DESCRIPTION
**Pull request by beenanner**
Quick hack to add a shortenURL for HTML output for URLs longer than 30 characters for #874. Code should probably be moved to a function and tests needed.

### CODE REVIEW

**Comment by soulgalore** [comment]
Cool I will test this tonight, think we could add this to more places.

**Comment by soulgalore** [comment]
And you could backport it to PerfCascade, I did a super simple version there nad it can be improved + it would be cool to use the same logic.

**Comment by soulgalore** [comment]
Did a quick check, I think we should aim for keeping the last part of the URL, that's the part that helps us identify the exact asset? I like how WPT does it:
screen shot 2016-06-05 at 20 22 09

What do you think @beenanner ?

**Comment by beenanner** [comment]
I agree and like it as well. Looks like they first grab from the file name then trim from the domain name if they have to. Let me take a look at their implementation to verify and see what I can do.

**Comment by beenanner** [comment]
Code for reference: https://github.com/WPO-Foundation/webpagetest/blob/9d1084d97765d0c15a1f5a822c60ec885522f0c6/www/waterfall.inc#L1100

**Comment by dmillerme7** [comment]
Nice job!

**Comment by beenanner** [comment]
If this works for everyone I can merge this into master for the next release.

Before
before


After
after

**Comment by soulgalore** [comment]
yes lets do it, Ive missed this one.

**Comment by tobli** [comment]
Looking good! One idea to build in this would be to remove the protocol from the url. Then indicate with https or not with an icon (e.g. a padlock). Could make the secure/not more easy to skim, regardless of the domain.

**Comment by beenanner** [comment]
Good idea let me file a ticket to investigate and implement that @tobli!

**Pull request merged**
