### PR TITLE
Change keys for PageXray assets to use URL instead of array position

### LINKED ISSUE #1313: Add URLs to assets in pagexray.pageSummary.assets
If you wanna track all the assets in Graphite (like the timings for all assets) that was possible in 3.x but in 4 we have taken a different approach to suppress the use of data. However we have it, so it could be cool to make it possible for people to use it.

Checkout what we send in the key *pagexray.pageSummary.assets*, we should be able to use that but then need to add the URL to the path. Maybe we could do a hack in how we generate the keys.

ping #1289

### PR DESCRIPTION
**Pull request by soulgalore**
The keys for assets in PageXray is broken when we send it to Graphite, because we cannot identify which asset we send, instead of the URL we use the position in the array.

However: Please don't send all the assets to Graphite, it will fill your disk.

Test like this:
<pre> tools/tcp-server.js</pre>
take the port and add it as Graphite port:
<pre>bin/sitespeed.js https://www.sitespeed.io -n 1 --graphite.host 127.0.0.1 --graphite.port PORT--metrics.filter *+</pre>

### CODE REVIEW

**Comment by beenanner** [comment]
Tested this out @soulgalore agreed please don't send all these to graphite 383 with sending the default metrics for sitespeed.io  verse 2160 metrics with adding in the URLs. Make sure that filter is only the URLs you want if you want to send metrics.  Eeeek!

**Comment by beenanner** [comment]
@soulgalore What is sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.*? It seems to be all the individual request URLs. Seems like that might be a bug? Or at least it seem like the data is being partially repeated across multiple keys.
```
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.transferSize 8429 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.contentSize 26406 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.headerSize 815 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.expires 600 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.status 200 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.timeSinceLastModified 1234000.67 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.headers.request.upgrade-insecure-requests 1 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.headers.response.age 1009300 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.headers.response.content-length 7614 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.headers.response.x-cache-hits 32 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.timing 515 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_.cookies 0 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.transferSize 4563 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.contentSize 3717 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.headerSize 846 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.expires 31536000 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.status 200 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.timeSinceLastModified 1234033.671 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.headers.response.age 1009299 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.headers.response.content-length 3717 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.headers.response.x-cache-hits 1 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.timing 53 1479876856
sitespeed_io.default.pageSummary.www_sitespeed_io._.chrome.native.pagexray.assets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.cookies 0 1479876856
```



```
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_.lastModification 1234000.67 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_.cacheTime 600 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_.size 26406 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_.timing 515 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_.requestCount 1 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.lastModification 1234033.671 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.cacheTime 31536000 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.size 3717 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.timing 53 1479876856
sitespeed_io.default.summary.www_sitespeed_io.chrome.native.aggregateassets.https___www_sitespeed_io_img_sitespeed-logo-2c_png.requestCount 1 1479876856
```

**Comment by beenanner** [comment]
How would multiple runs work would we need these to run through statsHelper.js to get the statistics goodies? Currently seems it only sends 1 set of results for both page level and summary level?

**Comment by soulgalore** [comment]
@beenanner aggregateassets is the "Toplist" of the most used assets, maybe we should add filter that removes that so you canät configure that the same way we do with HAR/screenshots.

so we only send the first timings for the first try, PageXray only uses the HAR from the first run, you correct. That is not perfect I agree but I think we should focus on other things since this is something we wanna avoid, however the  key structure is broken in the current version. In the old version I think we sent every run but we will have the same timestamp so I think Graphite just overrun the values right? Or aggregate them depending on configuration?

Yes correct would be statsHelper and then maybe choose to send max values and then generate the data directly from the HAR. But I think we should focus on other things first :)

**Comment by beenanner** [comment]
Ah yep that all make sense now! :-)

**Pull request merged**
