### PR TITLE
#2758 - fix: keep selected tab open accros runs

### PR DESCRIPTION
**Pull request by amtanq**
#2758 stated the issue of resetting the tab upon page change. This pull request adds a proxy over the navigation links and specifies new page to open with proper tab.

### CODE REVIEW

**Comment by soulgalore** [comment]
Hi @amtanq thanks for the PR and I really liked that you included a gif! Let me try that out tomorrow.

**Comment by soulgalore** [comment]
There where some lint issue with the pug-changes. I usually use https://pugjs.org/api/getting-started.html or depending on the editor you use, there are some available pug-linters.

**Comment by amtanq** [comment]
I'll check it you and fix them, would you please assign this issue to me?

**Comment by amtanq** [comment]
Closing in favour of #3409

**Pull request closed without merging**
